const fs = require('fs');

const files = [
  'components/visualizers/BinarySequence.tsx',
  'components/visualizers/Combination.tsx',
  'components/visualizers/Permutation.tsx',
  'components/visualizers/Subset.tsx'
];

files.forEach(file => {
  let code = fs.readFileSync(file, 'utf8');
  
  // Replace rounded, rounded-sm, rounded-md, rounded-lg, rounded-full, rounded-xl, rounded-2xl, etc.
  code = code.replace(/\brounded-[a-z0-9]+\b/g, '');
  code = code.replace(/\brounded\b/g, '');
  
  // Clean up any double spaces generated by the removal
  code = code.replace(/  +/g, ' ');

  fs.writeFileSync(file, code);
  console.log(`Stripped border-radius from ${file}`);
});
