export const CODE_SUDOKU = {
  cpp: `#include <vector>\n\nusing namespace std;\n\nbool isValid(const vector<vector<int>>& board, int row, int col, int num) {\n    int n = board.size();\n    int sub = 1;\n    while (sub * sub < n) sub++;\n    for (int i = 0; i < n; i++) {\n        if (board[row][i] == num) return false;\n        if (board[i][col] == num) return false;\n        if (board[sub * (row / sub) + i / sub][sub * (col / sub) + i % sub] == num) return false;\n    }\n    return true;\n}\n\nbool solveSudoku(vector<vector<int>>& board) {\n    int n = board.size();\n    int row = -1, col = -1;\n    for (int r = 0; r < n; r++) {\n        for (int c = 0; c < n; c++) {\n            if (board[r][c] == 0) {\n                row = r; col = c;\n                break;\n            }\n        }\n        if (row != -1) break;\n    }\n    if (row == -1) return true;\n\n    for (int num = 1; num <= n; num++) {\n        if (isValid(board, row, col, num)) {\n            board[row][col] = num;\n            if (solveSudoku(board)) return true;\n            board[row][col] = 0;\n        }\n    }\n    return false;\n}`,
  python: `def is_valid(board, row, col, num):\n    n = len(board)\n    sub = 1\n    while sub * sub < n:\n        sub += 1\n    for i in range(n):\n        if board[row][i] == num:\n            return False\n        if board[i][col] == num:\n            return False\n        if board[sub * (row // sub) + i // sub][sub * (col // sub) + i % sub] == num:\n            return False\n    return True\n\ndef solve_sudoku(board):\n    n = len(board)\n    row, col = -1, -1\n    for r in range(n):\n        for c in range(n):\n            if board[r][c] == 0:\n                row, col = r, c\n                break\n        if row != -1:\n            break\n    if row == -1:\n        return True\n\n    for num in range(1, n + 1):\n        if is_valid(board, row, col, num):\n            board[row][col] = num\n            if solve_sudoku(board): return True\n            board[row][col] = 0\n    return False`,
  javascript: `function isValid(board, row, col, num) {\n    const n = board.length;\n    let sub = 1;\n    while (sub * sub < n) sub++;\n    for (let i = 0; i < n; i++) {\n        if (board[row][i] === num) return false;\n        if (board[i][col] === num) return false;\n        const subRow = sub * Math.floor(row / sub) + Math.floor(i / sub);\n        const subCol = sub * Math.floor(col / sub) + i % sub;\n        if (board[subRow][subCol] === num) return false;\n    }\n    return true;\n}\n\nfunction solveSudoku(board) {\n    const n = board.length;\n    let row = -1, col = -1;\n    for (let r = 0; r < n; r++) {\n        for (let c = 0; c < n; c++) {\n            if (board[r][c] === 0) {\n                row = r; col = c;\n                break;\n            }\n        }\n        if (row !== -1) break;\n    }\n    if (row === -1) return true;\n\n    for (let num = 1; num <= n; num++) {\n        if (isValid(board, row, col, num)) {\n            board[row][col] = num;\n            if (solveSudoku(board)) return true;\n            board[row][col] = 0;\n        }\n    }\n    return false;\n}`
};

export const MAPPINGS_SUDOKU = {
  cpp: { 1: 17, 2: 19, 3: 20, 4: 21, 5: 22, 6: 31, 7: 32, 8: 33, 9: 34, 10: 35, 11: 38, 15: [9, 10, 11] },
  python: { 1: 15, 2: 17, 3: 18, 4: 19, 5: 20, 6: 27, 7: 28, 8: 29, 9: 30, 10: 31, 11: 32, 15: [7, 8, 9] },
  javascript: { 1: 15, 2: 17, 3: 18, 4: 19, 5: 20, 6: 29, 7: 30, 8: 31, 9: 32, 10: 33, 11: 36, 15: [6, 7, 10] }
};
